In [1]:
pip install pandas matplotlib numpy seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (3.0.2)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: numpy in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (2.4.4)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("zomato.csv")

In [4]:
df.head()

,Order_ID,Date,Time,Restaurant_Name,Food_Item,Order_Amount,Discount_Percentage,Final_Amount,Delivery_Time_Minutes,Payment_Method,Delivery_Status
0,ZOMF874EDB2,21-04-2026,03:01,KFC,Biryani,1143.34,15,971.84,62,UPI,Delayed
1,ZOM339D47F3,24-04-2026,17:05,Domino's,Burger,934.88,2,916.18,28,Cash,Delayed
2,ZOM64A4B20D,20-04-2026,00:35,Biryani House,Pasta,394.40,34,260.30,43,Wallet,Cancelled
3,ZOM71426B6D,26-04-2026,00:48,Pizza Hut,Sandwich,1232.03,27,899.38,24,Cash,Cancelled
4,ZOM4139A907,04-04-2026,02:24,Haldiram's,Sandwich,253.47,22,197.71,66,UPI,Delayed

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               10000 non-null  str
 1   Date                   10000 non-null  str
 2   Time                   10000 non-null  str
 3   Restaurant_Name        10000 non-null  str
 4   Food_Item              10000 non-null  str
 5   Order_Amount           10000 non-null  float64
 6   Discount_Percentage    10000 non-null  int64
 7   Final_Amount           10000 non-null  float64
 8   Delivery_Time_Minutes  10000 non-null  int64
 9   Payment_Method         10000 non-null  str
 10  Delivery_Status        10000 non-null  str
dtypes: float64(2), int64(2), str(7)
memory usage: 1.4 MB

In [6]:
df.shape

(10000, 11)

In [7]:
df.columns

Index(['Order_ID', 'Date', 'Time', 'Restaurant_Name', 'Food_Item',
       'Order_Amount', 'Discount_Percentage', 'Final_Amount',
       'Delivery_Time_Minutes', 'Payment_Method', 'Delivery_Status'],
      dtype='str')

In [8]:
df.isnull().sum()

Order_ID                 0
Date                     0
Time                     0
Restaurant_Name          0
Food_Item                0
Order_Amount             0
Discount_Percentage      0
Final_Amount             0
Delivery_Time_Minutes    0
Payment_Method           0
Delivery_Status          0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

In [12]:
df.dtypes

Order_ID                            str
Date                     datetime64[us]
Time                                str
Restaurant_Name                     str
Food_Item                           str
Order_Amount                    float64
Discount_Percentage               int64
Final_Amount                    float64
Delivery_Time_Minutes             int64
Payment_Method                      str
Delivery_Status                     str
dtype: object

In [13]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

In [14]:
cat_cols = df.select_dtypes(include=['object', 'string']).columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [15]:
df.columns = df.columns.str.strip()

In [16]:
for col in cat_cols:
    df[col] = df[col].str.strip()

In [17]:
df.isnull().sum()

Order_ID                 0
Date                     0
Time                     0
Restaurant_Name          0
Food_Item                0
Order_Amount             0
Discount_Percentage      0
Final_Amount             0
Delivery_Time_Minutes    0
Payment_Method           0
Delivery_Status          0
dtype: int64

In [18]:
df['Month'] = df['Date'].dt.month

In [19]:
df['Day_Name'] = df['Date'].dt.day_name()

In [20]:
df['Year'] = df['Date'].dt.year

In [21]:
df['Revenue_Category'] = pd.cut(
    df['Final_Amount'],
    bins=[0, 200, 500, 1000, 5000],
    labels=['Low', 'Medium', 'High', 'Very High']
)

In [22]:
df.describe()

,Date,Order_Amount,Discount_Percentage,Final_Amount,Delivery_Time_Minutes,Month,Year
count,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0,10000.0
mean,2026-04-15 12:33:41.760000,808.399920,19.782800,648.119492,42.416100,4.0,2026.0
min,2026-04-01 00:00:00,120.130000,0.000000,73.130000,15.000000,4.0,2026.0
25%,2026-04-08 00:00:00,467.840000,9.000000,365.332500,28.000000,4.0,2026.0
50%,2026-04-16 00:00:00,805.380000,20.000000,627.320000,42.000000,4.0,2026.0
75%,2026-04-23 00:00:00,1148.292500,30.000000,906.280000,57.000000,4.0,2026.0
max,2026-04-30 00:00:00,1499.990000,40.000000,1496.950000,70.000000,4.0,2026.0
std,NaN,398.722417,11.866133,336.956403,16.354593,0.0,0.0

In [23]:
df = df[df['Final_Amount'] > 0]

In [24]:
for col in cat_cols:
    print(col)
    print(df[col].unique())
    print("----------------")

Order_ID
<ArrowStringArray>
['ZOMF874EDB2', 'ZOM339D47F3', 'ZOM64A4B20D', 'ZOM71426B6D', 'ZOM4139A907',
 'ZOM45A8CDDD', 'ZOM9D77D330', 'ZOM50A42AD6', 'ZOM56E8C4C4', 'ZOM1DF199DD',
 ...
 'ZOM1531F02F', 'ZOM5A4844B6', 'ZOMEAD5B41D', 'ZOM1B7064BF', 'ZOM755BD3E9',
 'ZOM666262D4', 'ZOM053071CB', 'ZOM8F9FBA12', 'ZOMBE4FF149', 'ZOMA420D4E9']
Length: 10000, dtype: str
----------------
Time
<ArrowStringArray>
['03:01', '17:05', '00:35', '00:48', '02:24', '17:07', '06:45', '08:29',
 '22:59', '12:17',
 ...
 '01:58', '18:00', '05:17', '12:32', '00:06', '18:16', '07:49', '07:18',
 '19:11', '12:16']
Length: 1439, dtype: str
----------------
Restaurant_Name
<ArrowStringArray>
[            'KFC',        'Domino's',   'Biryani House',       'Pizza Hut',
      'Haldiram's',      'McDonald's',          'Subway',     'Burger King',
 'Barbeque Nation', 'Cafe Coffee Day']
Length: 10, dtype: str
----------------
Food_Item
<ArrowStringArray>
[     'Biryani',       'Burger',        'Pasta',     'Sandwich',
    'Ice Cream',        'Fries',       'Coffee',      'Noodles',
        'Pizza', 'Paneer Tikka']
Length: 10, dtype: str
----------------
Payment_Method
<ArrowStringArray>
['UPI', 'Cash', 'Wallet', 'Credit Card', 'Debit Card']
Length: 5, dtype: str
----------------
Delivery_Status
<ArrowStringArray>
['Delayed', 'Cancelled', 'Delivered']
Length: 3, dtype: str
----------------

In [25]:
df['Payment_Method'] = df['Payment_Method'].str.title()

In [26]:
df.rename(columns={
    'Restaurant_Name': 'Restaurant',
    'Food_Item': 'Food_Item',
    'Final_Amount': 'Revenue'
}, inplace=True)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               10000 non-null  str
 1   Date                   10000 non-null  datetime64[us]
 2   Time                   10000 non-null  str
 3   Restaurant             10000 non-null  str
 4   Food_Item              10000 non-null  str
 5   Order_Amount           10000 non-null  float64
 6   Discount_Percentage    10000 non-null  int64
 7   Revenue                10000 non-null  float64
 8   Delivery_Time_Minutes  10000 non-null  int64
 9   Payment_Method         10000 non-null  str
 10  Delivery_Status        10000 non-null  str
 11  Month                  10000 non-null  int32
 12  Day_Name               10000 non-null  str
 13  Year                   10000 non-null  int32
 14  Revenue_Category       10000 non-null  category
dtypes: category(1), datetime64[us](1), float64(2), int32(2), int64(2), str(7)
memory usage: 1.5 MB

In [29]:
df.to_csv("cleaned_zomato.csv", index=False)

In [30]:
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (1.1.3)
Requirement already satisfied: sqlalchemy in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vedant swami\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)

In [31]:
from sqlalchemy import create_engine

# Load CSV file
df = pd.read_csv("cleaned_zomato.csv")

# Check first 5 rows
print(df.head())

# MySQL connection details
username = "root"
password = "Rutu9724"
host = "localhost"
port = "3307"
database = "zomato_p"

# Create MySQL engine
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Table name in MySQL
table_name = "customer"

# Upload DataFrame to MySQL
df.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data uploaded successfully!")

# Read sample data from MySQL
sample_data = pd.read_sql(
    "SELECT * FROM customer LIMIT 5;",
    engine
)

# Display sample data
print(sample_data)

      Order_ID        Date   Time     Restaurant Food_Item  Order_Amount  \
0  ZOMF874EDB2  2026-04-21  03:01            KFC   Biryani       1143.34
1  ZOM339D47F3  2026-04-24  17:05       Domino's    Burger        934.88
2  ZOM64A4B20D  2026-04-20  00:35  Biryani House     Pasta        394.40
3  ZOM71426B6D  2026-04-26  00:48      Pizza Hut  Sandwich       1232.03
4  ZOM4139A907  2026-04-04  02:24     Haldiram's  Sandwich        253.47

   Discount_Percentage  Revenue  Delivery_Time_Minutes Payment_Method  \
0                   15   971.84                     62            Upi
1                    2   916.18                     28           Cash
2                   34   260.30                     43         Wallet
3                   27   899.38                     24           Cash
4                   22   197.71                     66            Upi

  Delivery_Status  Month  Day_Name  Year Revenue_Category
0         Delayed      4   Tuesday  2026             High
1         Delayed      4    Friday  2026             High
2       Cancelled      4    Monday  2026           Medium
3       Cancelled      4    Sunday  2026             High
4         Delayed      4  Saturday  2026              Low
Data uploaded successfully!
      Order_ID        Date   Time     Restaurant Food_Item  Order_Amount  \
0  ZOMF874EDB2  2026-04-21  03:01            KFC   Biryani       1143.34
1  ZOM339D47F3  2026-04-24  17:05       Domino's    Burger        934.88
2  ZOM64A4B20D  2026-04-20  00:35  Biryani House     Pasta        394.40
3  ZOM71426B6D  2026-04-26  00:48      Pizza Hut  Sandwich       1232.03
4  ZOM4139A907  2026-04-04  02:24     Haldiram's  Sandwich        253.47

   Discount_Percentage  Revenue  Delivery_Time_Minutes Payment_Method  \
0                   15   971.84                     62            Upi
1                    2   916.18                     28           Cash
2                   34   260.30                     43         Wallet
3                   27   899.38                     24           Cash
4                   22   197.71                     66            Upi

  Delivery_Status  Month  Day_Name  Year Revenue_Category
0         Delayed      4   Tuesday  2026             High
1         Delayed      4    Friday  2026             High
2       Cancelled      4    Monday  2026           Medium
3       Cancelled      4    Sunday  2026             High
4         Delayed      4  Saturday  2026              Low